dist: trusty
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cmake

before_install:
  - pip install --user cpp-coveralls      
    
script:
  # Build and test
  - mkdir -p build
  - cd build
  - cmake .. 
  - cmake --build .
  - ctest
  
after_success:
  - coveralls --root . -E ".*CMakeFiles.*"

